/** Auto-generated by scripts/sync-kenya-gallery.mjs from kenya-gallery.allowlist.json */
export const KENYA_GALLERY_IMAGES = [
  "/kenya/nairobi-expressway.png",
  "/kenya/flower-farm-roses.jpg",
  "/kenya/tea-farm-kenya.jpg",
  "/kenya/mt-longonot.jpg",
  "/kenya/golf-course-nairobi.jpg",
  "/kenya/Lake-Victoria-Dhow.jpg",
  "/kenya/maasai-kenya.jpg"
] as const;
export const KENYA_GALLERY_CACHE_KEY = "/kenya/nairobi-expressway.png|/kenya/flower-farm-roses.jpg|/kenya/tea-farm-kenya.jpg|/kenya/mt-longonot.jpg|/kenya/golf-course-nairobi.jpg|/kenya/Lake-Victoria-Dhow.jpg|/kenya/maasai-kenya.jpg";
