/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as MapRouteImport } from './routes/map'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminloginRouteImport } from './routes/adminlogin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminPropertiesRouteImport } from './routes/admin/properties'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminDraftsIndexRouteImport } from './routes/admin/drafts/index'
import { Route as AdminDraftsNewRouteImport } from './routes/admin/drafts/new'
import { Route as AdminDraftsDraftIdRouteImport } from './routes/admin/drafts/$draftId'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminloginRoute = AdminloginRouteImport.update({
  id: '/adminlogin',
  path: '/adminlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDraftsIndexRoute = AdminDraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDraftsNewRoute = AdminDraftsNewRouteImport.update({
  id: '/drafts/new',
  path: '/drafts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDraftsDraftIdRoute = AdminDraftsDraftIdRouteImport.update({
  id: '/drafts/$draftId',
  path: '/drafts/$draftId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/adminlogin': typeof AdminloginRoute
  '/contact': typeof ContactRoute
  '/map': typeof MapRoute
  '/saved': typeof SavedRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/drafts/$draftId': typeof AdminDraftsDraftIdRoute
  '/admin/drafts/new': typeof AdminDraftsNewRoute
  '/admin/drafts/': typeof AdminDraftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adminlogin': typeof AdminloginRoute
  '/contact': typeof ContactRoute
  '/map': typeof MapRoute
  '/saved': typeof SavedRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/drafts/$draftId': typeof AdminDraftsDraftIdRoute
  '/admin/drafts/new': typeof AdminDraftsNewRoute
  '/admin/drafts': typeof AdminDraftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/adminlogin': typeof AdminloginRoute
  '/contact': typeof ContactRoute
  '/map': typeof MapRoute
  '/saved': typeof SavedRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/drafts/$draftId': typeof AdminDraftsDraftIdRoute
  '/admin/drafts/new': typeof AdminDraftsNewRoute
  '/admin/drafts/': typeof AdminDraftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/adminlogin'
    | '/contact'
    | '/map'
    | '/saved'
    | '/admin/bookings'
    | '/admin/leads'
    | '/admin/properties'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/properties/$slug'
    | '/admin/'
    | '/properties/'
    | '/admin/drafts/$draftId'
    | '/admin/drafts/new'
    | '/admin/drafts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adminlogin'
    | '/contact'
    | '/map'
    | '/saved'
    | '/admin/bookings'
    | '/admin/leads'
    | '/admin/properties'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/properties/$slug'
    | '/admin'
    | '/properties'
    | '/admin/drafts/$draftId'
    | '/admin/drafts/new'
    | '/admin/drafts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/adminlogin'
    | '/contact'
    | '/map'
    | '/saved'
    | '/admin/bookings'
    | '/admin/leads'
    | '/admin/properties'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/properties/$slug'
    | '/admin/'
    | '/properties/'
    | '/admin/drafts/$draftId'
    | '/admin/drafts/new'
    | '/admin/drafts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminloginRoute: typeof AdminloginRoute
  ContactRoute: typeof ContactRoute
  MapRoute: typeof MapRoute
  SavedRoute: typeof SavedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminlogin': {
      id: '/adminlogin'
      path: '/adminlogin'
      fullPath: '/adminlogin'
      preLoaderRoute: typeof AdminloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drafts/': {
      id: '/admin/drafts/'
      path: '/drafts'
      fullPath: '/admin/drafts/'
      preLoaderRoute: typeof AdminDraftsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drafts/new': {
      id: '/admin/drafts/new'
      path: '/drafts/new'
      fullPath: '/admin/drafts/new'
      preLoaderRoute: typeof AdminDraftsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drafts/$draftId': {
      id: '/admin/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/admin/drafts/$draftId'
      preLoaderRoute: typeof AdminDraftsDraftIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDraftsDraftIdRoute: typeof AdminDraftsDraftIdRoute
  AdminDraftsNewRoute: typeof AdminDraftsNewRoute
  AdminDraftsIndexRoute: typeof AdminDraftsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDraftsDraftIdRoute: AdminDraftsDraftIdRoute,
  AdminDraftsNewRoute: AdminDraftsNewRoute,
  AdminDraftsIndexRoute: AdminDraftsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminloginRoute: AdminloginRoute,
  ContactRoute: ContactRoute,
  MapRoute: MapRoute,
  SavedRoute: SavedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
